FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o my-microservice ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/my-microservice .
CMD ["../my-microservice"]
